### ISSUE TITLE
time_per_step() should return f64, not Duration.

### ISSUE THREAD

**Issue by krdln** [mitsuhiko/indicatif#10]
Currently, the `Estimate::time_per_step` returns `Duration`. This limits the precision and range that time per step can represent – `Duration` always stores multiples of nanosecods. Moreover, if your step takes less than nanosecond, time per step would be 0, and the ETA would be always 00:00:00. This is how I discovered the bug.

TLDR: Here is list of speeds that indicatif currently supports: :)
…, ¼GB/s, ⅓GB/s, ½GB/s, 1GB/s, ∞YB/s.

**Comment by lambdaupb** [comment]
I doubt this was a problem with Duration. After looking at the code it uses f64 in the buf vector instead of Durations. Duration supports addition and there is no need to convert to f64 before summing it up.

Floats are imprecise by construction. The time API works on nanoseconds internally and so should we. conversion to f64 should be the last step.

**Comment by krdln** [comment]
Perhaps I've made a mistake by suggesting a solution in the issue's title instead of just describing it.

> After looking at the code it uses f64 in the buf vector instead of Durations. Duration supports addition and there is no need to convert to f64 before summing it up.

I think storing actual durations as `Duration` would be perfectly fine. It's different here though — what we store here is not a duration, but rather speed^−1 — duration divided by number of steps. So the loss of precision happens anyway, in the moment of division itself and by rounding the `time_per_step` to nanoseconds. By the way, `f64` is able to store a number of nanoseconds losslessly up to about 7 months (and µs to about 500 years), so I wouldn't worry too much about the loss of precision.

**Comment by lambdaupb** [comment]
I mean why store the result of a lossy calculation instead of both values for each step. Then sum the components separately and divide afterwards.

Although I'm wondering why its not just using `0.9*last + 0.1*current` for estimating instead of this buffer construction.

**Comment by kayru** [comment]
Encountered this issue also. The nanosecond precision used by `Duration` is really not enough when dealing with time per step calculations. Rates of >1e9/s can be relatively easy to achieve when dealing with things like reading bytes from modern SSDs. Using `f64` specifically to compute `Estimate::time_per_step()` is quite reasonable, as it is not dealing with precise durations.

**Comment by djc** [comment]
I'm happy to review a PR for this.

**Comment by kayru** [comment]
Incoming!
