### ISSUE TITLE
impl Drop makes ProgressBar not being a proper copyable object

### ISSUE THREAD

**Issue by Aetf** [mitsuhiko/indicatif#114]
The documentation of `ProgressBar` says
> The progress bar is an Arc around an internal state. When the progress bar is cloned it just increments the refcount which means the bar is shared with the original one.

However, due to the `impl Drop for ProgressBar` implicitly finishes the bar, any out-of-scope copy of the `ProgressBar` will make other copies finish. This is especially bad when combined with `MultiProgress`, where one thread is joining on `MultiProgress`. In this case, the early finish of the `ProgressBar` makes subsequent calls to `ProgressBar` via other copies panic because the `MultiProgress` is gone.

The Drop should be implemented on the refcounted state, rather than on the `ProgressBar` itself.

Minimal Reproducible Example:

```
use std::thread;
use std::time::Duration;
use indicatif::{ProgressBar, MultiProgress};

fn main() {
    let m = MultiProgress::new();
    let pb = m.add(ProgressBar::new(10));

    // start a thread to drive MultiProgress
    let h = thread::spawn(move || {
        m.join().unwrap();
        println!("Done in thread, droping MultiProgress");
    });

    {
        let pb2 = pb.clone();
        for _ in 0..10 {
            pb2.inc(1);
            thread::sleep(Duration::from_millis(50));
        }
    }

    h.join().unwrap();

    println!("Shouldn't have gone this far, as we haven't call finish yet");

    pb.set_message("Done");
    pb.finish();

    println!("Done in main");
}
```

This panics at `pb.set_message("Done");`

**Comment by mitsuhiko** [comment]
I tried to fix this by just checking for the refcount in the drop but that just makes it deadlock your example. Don't have the time to investigate this at the moment but if you know how to fix this I can pull a PR.

**Comment by Aetf** [comment]
Deadlock is the intended behavior because the driver thread shouldn't finish.

But I think implementing `Drop` directly on `ProgressState` is more elegant than your current method checking the reference count. I made a PR #120 with my version of the fix and an updated test to demonstrate the issue.

**Comment by mitsuhiko** [comment]
Closing this.
