### ISSUE TITLE
"fatal runtime error: out of memory" for a ProgressBar with length of 0, on finish().

### ISSUE THREAD

**Issue by dcbishop** [mitsuhiko/indicatif#12]
Might seem silly to have a progress bar with 0 size but it can come up in real world use cases. For example file system operations like copy with an empty file.

```
extern crate indicatif;
use indicatif::ProgressBar;

fn main() {
    let pb = ProgressBar::new(0);
    pb.finish();
}
```

**Comment by alex** [comment]
The reason this happens is: https://github.com/mitsuhiko/indicatif/blob/master/src/progress.rs#L205-L213

`pct` is `nan`, and so `(pct * width as f32)` is `nan`, and apparently casting `nan` to `usize` gives you a giant integer.
