### ISSUE TITLE
Can't print messages with finish_with_message function

### ISSUE THREAD

**Issue by mrprofessor** [mitsuhiko/indicatif#136]
my function
```rust
#[allow(unused_variables)]
fn main() {
    use indicatif::ProgressBar;
    let bar = ProgressBar::new(10000);

    println!("Fake downloads");
    for item in 1..10000 {
        bar.inc(1);
    }
    bar.finish_with_message("done");
}
```

Output:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/11652364/70091450-20abbd00-1642-11ea-89ea-0b3246dcba90.png">

**Comment by mibac138** [comment]
This is expected. As per the documentation for `set_message`:
> For the message to be visible, `{msg}` must be present in the template (see `ProgressStyle`).

In order to fix this you need to call `set_style` after `ProgressBar::new` and modify the template to include the `{msg}` placeholder
