### ISSUE TITLE
MultiProgress bar flickers#2

### ISSUE THREAD

**Issue by inv2004** [mitsuhiko/indicatif#143]
I did another try of indicatif 0.13.0, and found that as soon as I only one ProgressBar into MultiProgress it starts to flicker the same I described in https://github.com/mitsuhiko/indicatif/issues/42.

Regards,

**Comment by mibac138** [comment]
Please submit a code reproducing the problem and your environment

**Comment by inv2004** [comment]
windows-10. conemu.

It is just a bit modified example/multi.rs
If I change ranges for 10k 100k 10k - it stops flicker.
https://gist.github.com/127aff606d2d5bf5e8ab9197c7a9b71b

**Comment by Deniskore** [comment]
I got the same flickering problem using MultiProgress bar with thread pool.
The code is almost the same as in the example.

**Comment by Deniskore** [comment]
```rust
    let m = MultiProgress::new();
    m.set_move_cursor(true);
```
Solves the problem with flickering

**Comment by inv2004** [comment]
@Deniskore 
Just checked - it helped. Thank you.
