### ISSUE TITLE
Feature Request: Use braille characters to create better looking spinners

### ISSUE THREAD

**Issue by heyitspuggo** [mitsuhiko/indicatif#176]
A similar repo that has a (extremely) similar function is [braille-pattern-cli-loading-indicator].(https://github.com/6/braille-pattern-cli-loading-indicator)

If this pattern could be implemented, it would look awesome in the terminal for loading.

**Comment by nlinker** [comment]
Could be customized with https://docs.rs/indicatif/0.14.0/indicatif/struct.ProgressStyle.html#method.tick_chars, no?

**Comment by heyitspuggo** [comment]
Oh, I'm just really blind. Thanks, though. :suspect:
