### ISSUE TITLE
ETA and per_sec values can be very wrong

### ISSUE THREAD

**Issue by segfaultsourcery** [mitsuhiko/indicatif#211]
Hi,

I discovered that the ETA (and `per_sec`) values can be off by orders of magnitude, especially when you don't start from zero.
This is especially problematic for me since I want to use this library to hook into processes that may already have been running for a while.

Minimal example:
```rust
use std::cmp::min;
use std::thread;
use std::time::Duration;
use indicatif::{ProgressBar, ProgressStyle};
fn main() {
    let mut current = 5_000_000;
    let total = 10_000_000;
    let pb = ProgressBar::new(total);
    pb.set_style(
        ProgressStyle::default_bar()
            .template(
                "[{elapsed_precise}/{eta_precise}] [{bar:40.cyan/blue}] {pos}/{len} ({per_sec})",
            )
            .progress_chars("#>-"),
    );
    while current < total {
        let new = min(current + 100000, total);
        current = new;
        pb.set_position(new);
        thread::sleep(Duration::from_secs(1));
    }
    pb.finish_with_message("current");
}
```

We start at 5M, we go up to 10M, and every second we add 0.1M.

Here's the output after 3 seconds:

```bash
$ cargo run
[00:00:03/00:00:02] [#####################>------------------] 5400000/10000000 (3558718/s)
```

As you can tell, since the code adds 100k every second, both the ETA and the `per_sec` values are off by an order of magnitude.

```bash
$ cargo run
[00:00:44/00:00:02] [######################################>-] 9500000/10000000 (228362/s)
```

The numbers stay wrong until the bitter end. I'd be happy to fix this problem myself, if I can have a few pointers! :)

**Comment by segfaultsourcery** [comment]
The dependencies:

```toml
[dependencies]
indicatif = "^0.15"
```

**Comment by mibac138** [comment]
If you aren't starting from `0` you are supposed to use `ProgressBar::reset_eta` to prevent this problem. Check the `download-eta` example and PR #171 for an example.

**Comment by segfaultsourcery** [comment]
Oh I see! Sorry about that :)
