### ISSUE TITLE
ProgressBar does not get redrawn

### ISSUE THREAD

**Issue by matthiasbeyer** [mitsuhiko/indicatif#212]
I have a multi-threaded program where I add a ProgressBar with length 100 to a multi bar and then continue to tick() and set_length() the bar (increasing values, as I see in the log output). The bar gets drawn when it initializes, but not afterwards until I finish() it.

How can I debug what's happening here?

Unfortunately, I cannot share the code. Hope you understand and that you can guide me through the process of debugging this anyways!

**Comment by matthiasbeyer** [comment]
After the finish() call, the bar gets drawn as complete, but it does not redraw the bar but draws a new bar instead. Maybe that's a hint for you what's happening here.

**Comment by mibac138** [comment]
Do you call `MultiProgress::join`? When a `ProgressBar` is connected to a `MultiProgress` calling `ProgressBar::tick` sends new data to `MultiProgress` but the `MultiProgress` itself needs to be updated as well.

**Comment by matthiasbeyer** [comment]
I call `MultiProgress::join` after all threads that have a `ProgressBar` that was added to the multi-bar are finished (futures are `await`ed), yes.

**Comment by matthiasbeyer** [comment]
Do you mean I need to `join` while updating the progress bars?

**Comment by mibac138** [comment]
> Do you mean I need to `join` while updating the progress bars?

Yes, you need. That should fix the issue. Keep in mind that `join` blocks the thread until all `ProgressBar`s have finished.

**Comment by matthiasbeyer** [comment]
It is really inconvenient that I have to manually wrap the `MultiProgress` object in an `Arc` and move it around, then.

**Comment by matthiasbeyer** [comment]
Hm, the longer I try, the more I get the impression that indicatif is not a good choice for `async-await` codebases.

**Comment by matthiasbeyer** [comment]
Okay, I fixed my issue.
Thanks for your support!

**Comment by flopacero** [comment]
@matthiasbeyer what was your final approach to the problem?

**Comment by matthiasbeyer** [comment]
Calling `MultiProgress::join()`.

**Comment by flopacero** [comment]
Right. There's no way around. Just need some tricks giving the blocking nature of `MultiProgress::join` Thanks!
