### ISSUE TITLE
Feasibility of `regex` removal

### ISSUE THREAD

**Issue by fosskers** [mitsuhiko/indicatif#217]
Hi there, this is a great project and I use it in a few of my applications.

[regex](https://lib.rs/crates/regex) is a famously heavy dependency which incurs a significant increase in binary size to downstream executables. Size-conscious terminal applications may not want to bear that cost. How feasible would it be to replace the usage of `regex` in `indicatif`, or perhaps hide its use behind a feature flag?

I did some poking around to trace `regex`'s use, and found this trail:
```
ProgressBar::println() -> ProgressStyle::format_state() -> utils::expand_template() -> regex 
```
And even then, the call to `format_state` was within an `if` statement. There is only one other call to `format_state()`, and it too is behind an `if`. How central to normal usage is `format_state()`, compared to its sibling `format_bar()`? Are there grounds enough here to try and hide it behind a `regex` feature?

Or, could the regex usage in `expand_template()` be replaced with reasonable effort?

**Comment by fosskers** [comment]
Now that I look closer at the warnings left over, it seems that `format_bar()` is entirely unused if `format_state()` is gone.

**Comment by marienz** [comment]
If I read the code right, introducing a `regex` feature for `format_state` is not feasible:

- It's used to expand templates (the ones received by `ProgressStyle::template()`) for drawing any progress bars to the screen (not just from `println()`, from anything updating progress bar state, see `update_and_draw`).
- Even if you don't need custom templates, the default styles just use string templates that get expanded when drawing the same way custom ones are. There is no "compiled template" datastructure the defaults could use instead.

So it's very central to normal usage: if removed, the API would work fine but nothing could get drawn to the screen :)

`format_state` would have to be reimplemented without `regex`, or everything refactored to use a separate datastructure to represent a parsed template so the defaults can use that (or both, if having such a datastructure is deemed useful independently from regex removal). That does look doable with reasonable effort, but not important enough to me right now to take a stab at it, sorry...

(There's also a regex dependency in indicatif's "console" dependency, but it looks like it's only needed for some escape sequence scanning code indicatif does not need, and can already be turned off through features.)

**Comment by mitsuhiko** [comment]
In theory someone could provide a patch. I do think though that we could use the non unicode version of regex here.
