### ISSUE TITLE
Single line progress

### ISSUE THREAD

**Issue by pickfire** [mitsuhiko/indicatif#224]
Right now the single line progress will leave the cursor on the second line, which makes it looks less elegant. Maybe have a single line progress bar version that allows putting the cursor at the back or at the front (or even hide it) while displaying another progress bar, without having to have an extra line.

**Comment by sigmaSd** [comment]
New discussion here https://github.com/mitsuhiko/indicatif/issues/334

**Comment by djc** [comment]
Let's close this in favor of the other issue, which has more discussion.
