### ISSUE TITLE
Allow to print (log) messages above the progress bar

### ISSUE THREAD

**Issue by bomgar** [mitsuhiko/indicatif#27]
Currently messages with `println!()` are overwritten by the next progress bar tick. It would be awesome to have something like `pb.log("hello")` and have hello printed with the next tick above the bars.

**Comment by mitsuhiko** [comment]
You can use newlines in the template. There are two values that can be set: prefix and message and both can be set. So you can set the "line above" to the prefix and render it.

**Comment by bomgar** [comment]
Does this work with multi bars?

**Comment by mitsuhiko** [comment]
Yes.

**Comment by bomgar** [comment]
I have 4 worker threads with steady_tick enabled. Every time they finish a task I want to log that. Changing the prefix just multiplies the bars for me. The result looks really strange. Surprisingly the tick_chars further update still get updated. It also doesn't really write above all bars. Just above the one the thread is updating which is not what i want.

I don't think this is a clean way to write log messages.

**Comment by mitsuhiko** [comment]
You can use different styles for different bars. So the first bar can be used to write out messages.

**Comment by bomgar** [comment]
Ok i guess I could try that. But doesn't that mean all threads must have access to the first bar or send messages to the thread responsible for the first bar? This seems like my code will become a lot less readable. This isn't a clean API. It feels like a really dirty workaround.

**Comment by mitsuhiko** [comment]
I’m gladly accepting patches but I am not sure how this could be done nicer currently.
