### ISSUE TITLE
Question: define and use multiple msg in template

### ISSUE THREAD

**Issue by Rudo2204** [mitsuhiko/indicatif#291]
I have been looking at the docs but I can't figure out how to use multiple `msg` in indicatif's template. It seems like you are limited to only one `msg`. I think not using template feature is also fine, I simply want to have a way to use multiple custom messages with a progress bar.  Is there any way I can do this?

**Comment by djc** [comment]
I'm not sure what this would mean. Do you mean messages on multiple lines, or multiple messages on a single line?

**Comment by Rudo2204** [comment]
Sorry for the ambiguity. I want multiple messages on a single line, with progress bar. Something like `{spinner} {msg1} {bar} {msg2} {eta}`

**Comment by djc** [comment]
I suppose you can use `set_style()` to update the style (including the template) at any time, so if you just use literal messages in your templates this should work out okay?

**Comment by Rudo2204** [comment]
Aah! That would work out for my case. I'm closing this issue. Thank you for the quick solution.
