### ISSUE TITLE
Message and position seem out of sync

### ISSUE THREAD

**Issue by joerivanruth** [mitsuhiko/indicatif#292]
In the following test program, I update both the message and the position a couple of times. However, the bar position changes seem to be picked up only after the next update.

I've also tried it the other way around, first setting the position and then the message. In that case, the message changes are picked up only after the next update.

Is this a bug or am I misunderstanding the intent of the API somehow?

Best regards,

Joeri

```Rust
use indicatif::{ProgressBar, ProgressStyle};
use std::{thread, time::Duration};

fn main() {
    let style = ProgressStyle::default_bar().template("{msg} {wide_bar}");
    let bar = ProgressBar::new(3).with_style(style);

    let update = |x: u64| {
        bar.set_message(format!("x={}", x));
        bar.set_position(x);
        thread::sleep(Duration::from_secs(2));
    };

    // First two seconds: (OK)
    //     Expect: x=0, bar at 0%
    //     See: x=0, bar at 0%
    update(0);

    // After two seconds: (NOT OK)
    //     Expect: x=1, bar at 33%
    //     See: x=1, bar still at 0%
    update(1);

    // After two more seconds: (NOT OK)
    //     Expect x=3, bar at 100%
    //     See: x=3, bar at 33%
    update(3);
}
```

**Comment by djc** [comment]
Good catch! This appears to be fixed on main, through the draw pacing changes in #284.
