### ISSUE TITLE
Weird rounding by HumanDuration

### ISSUE THREAD

**Issue by Armavica** [mitsuhiko/indicatif#294]
Hi, first of all thank you for this very nice library.
However, a duration of 1 hour 59 min and 59 seconds is rounded down to "1 h" (and similarly for other numbers), which seems a bit surprising to me. I would expect the switch from "2 h" to "1 h" to happen at 1 hour and 30 minutes.
I think there is only a couple of lines to change in this block https://github.com/mitsuhiko/indicatif/blob/main/src/format.rs#L44 to change this behaviour. Would you mind if I sent a pull request for this?

**Comment by djc** [comment]
Sounds good! It would be great if you can also add some unit tests in that file to clarify the intended behavior.
