### ISSUE TITLE
No way to customize template parameters/units

### ISSUE THREAD

**Issue by redzic** [mitsuhiko/indicatif#299]
Currently, I have forked `indicatif` to add an easier way to display the frames per second of an encode. I did this because calling `set_message` seems to add significant "flashing" to the progress bar, whereas just using the templates does not seem to cause this issue. Furthermore, I do not want to have to duplicate data structures for keeping track of the frames per second when this is already kept track of by a `ProgressBar`. For example, `tqdm` has a way of specifying the units and using more precision for the iterations per second, which doesn't seem to be currently possible with indicatif, unless the unit you want to use is bytes per second.

Maybe there could be some function to be called that adds user-defined functions to the template parser.

**Comment by djc** [comment]
Can you be more concrete about the changes you made/what kind of data you want to show, and what is missing to support that?

**Comment by redzic** [comment]
In short, I want to be able to define a function that can reference the `ProgressState` which is called during template expansion, in [`format_state`](https://github.com/redzic/indicatif/blob/7fc8131591e41d1d26edb8f2e6fefec50ff8cdbc/src/style.rs#L228). Currently, I have achieved this by just forking indicatif and adding those functions myself.

Here are the changes that I have made to support my use case (the code doesn't seem to inline in github for me for whatever reason):

https://github.com/redzic/indicatif/blob/7fc8131591e41d1d26edb8f2e6fefec50ff8cdbc/src/style.rs#L264
https://github.com/redzic/indicatif/blob/7fc8131591e41d1d26edb8f2e6fefec50ff8cdbc/src/state.rs#L119-L127

For my use case, I would like to display the iterations per second with more precision and with a different unit. If you use `per_sec`, then it it has no decimal precision, and the unit at the end is always `/s`. I would like a specifiable amount of precision, and the ability to change the unit to `fps` or anything else.

Using [`set_message`](https://docs.rs/indicatif/0.16.2/indicatif/struct.ProgressBar.html#method.set_message) to achieve this causes a lot of flickering (which doesn't happen otherwise), and requires me to keep a redundant copy of data related to tracking the iterations per second. Basically, it is more error-prone and causes unnecessary overhead for my use case.

I was thinking that the easiest way to support this is to just have the ability to dynamically add keys that `format_state` calls. Perhaps [`ProgressStyle`](https://github.com/redzic/indicatif/blob/7fc8131591e41d1d26edb8f2e6fefec50ff8cdbc/src/style.rs#L13) could be updated to hold a hash map of strings to functions that `format_state` calls.

I could take a stab at implementing this if the design is good, otherwise there could be some discussion to be had as to how to achieve this.

**Comment by djc** [comment]
I think it would be okay to have support for custom template keys which get a `&ProgressState`. Let's only expose `ProgressState::position()` publicly for now?

**Comment by redzic** [comment]
Fixed by #301 ! Thanks

**Comment by djc** [comment]
Thank you for getting it done!
