### ISSUE TITLE
bytes_per_sec saturates to 0 B/s when reaching multiple GiB/s

### ISSUE THREAD

**Issue by andrewchambers** [mitsuhiko/indicatif#303]
My backup tool displays bytes_per_sec as an upload progress bar, but when the speeds get into the multiple GiB/s the displayed speed wraps  back around to 0 B/s.

**Comment by djc** [comment]
Can you try main? We made some changes that I think are relevant.

**Comment by andrewchambers** [comment]
This seems to have resolved it.
