### ISSUE TITLE
examples/multi.rs maybe has an error

### ISSUE THREAD

**Issue by bqdong** [mitsuhiko/indicatif#311]
![image](https://user-images.githubusercontent.com/52027654/133274152-02070475-8590-42d0-8815-c617d4872a4c.png)
Hello, I'm a newbie. [this line](https://github.com/mitsuhiko/indicatif/blob/27c8cc3078b65aa2573dbe673a00471d6662698c/examples/multi.rs#L50) seems have an error!

**Comment by djc** [comment]
I don't think it does -- I think you took the example from the main branch but you're using a released version of the library in your project. You'll want to use [this version](https://github.com/mitsuhiko/indicatif/blob/0.16.x/examples/multi.rs) instead.

**Comment by bqdong** [comment]
You're right. Thanks!
