### ISSUE TITLE
per_sec in 0.17 shows too many digits

### ISSUE THREAD

**Issue by mpetri** [mitsuhiko/indicatif#312]
I'm trying the new 0.17 release and I noticed the {per_sec} output now uses f64. However, when trying to use it in a sample program it uses too much precision: 

for example: TPS: 199.5687279244087/s

**Comment by djc** [comment]
That's fair. What do you think about #313 as a fix?

**Comment by mpetri** [comment]
looks good!

**Comment by djc** [comment]
Thanks for the review!
