### ISSUE TITLE
Question: set message while using rayon

### ISSUE THREAD

**Issue by Lukas1818** [mitsuhiko/indicatif#320]
It is possible to set the message while I did use rayon?
I would like to create a progressbar simlar to `cargo run`, where you can see, with files are build behind the progress bar.
```
Building [===>                      ] 30/195: untrusted, termcolor, ansi_term, typenum(build.rs), regex-syntax, lazy_static, spin, shlex 
```
The problem is that that `.progress_with(pb)` take the owner ship of `pb` so I can not call `pb.set_message(msg)` anymore.

```rust
	let pb = ProgressBar::new(stickerpack.stickers.len() as u64);
	pb.set_style(
		ProgressStyle::default_bar()
			.template("[{wide_bar:.cyan/blue}] {pos:>3}/{len} {msg}")
			.progress_chars("#> "),
	);
	stickerpack
		.stickers
		.par_iter()
		.progress_with(pb)
		.enumerate()
		.map(|(i, sticker)| {
			pb.set_message(format!("download sticker {}", sticker.file_id))
			pb.set_message(format!("convert sticker {}", sticker.file_id))
```
Full code: https://github.com/Lukas1818/mstickereditor/blob/9c083d6fdcde87af10c09483f982bc9f04b70929/src/main.rs#L230

```rust
rror[E0382]: borrow of moved value: `pb`
   --> src/main.rs:240:8
    |
229 |     let pb = ProgressBar::new(stickerpack.stickers.len() as u64);
    |         -- move occurs because `pb` has type `ProgressBar`, which does not implement the `Copy` trait
...
238 |         .progress_with(pb)
    |                        -- value moved here
239 |         .enumerate()
240 |         .map(|(i, sticker)| {
    |              ^^^^^^^^^^^^^^ value borrowed here after move
241 |             pb.set_message(format!("dowload sticker {}", sticker.file_id));
    |             -- borrow occurs due to use in closure


```

**Comment by djc** [comment]
A `ProgressBar` contains an `Arc` internally, so you're expected to just clone it for this sort of thing.

**Comment by Lukas1818** [comment]
Thanks I did did not know I can clone it. I thought this would create a new independence bar.

Sadly it seams that the bar is not updated even after I call `pb.tick()` only if I does use `pb.enable_steady_tick(200);` or one thread is finished the the bar is updated.

**Comment by djc** [comment]
What version are you using? That sounds like a separate issue which might have been addressed on the main branch, maybe see if that works for you?

**Comment by Lukas1818** [comment]
I did use 0.16.2.

**Comment by djc** [comment]
Okay, can you file a new issue about this?

**Comment by Lukas1818** [comment]
> Okay, can you file a new issue about this?

done: https://github.com/mitsuhiko/indicatif/issues/321
