### ISSUE TITLE
Extra line after the progress bar

### ISSUE THREAD

**Issue by ishitatsuyuki** [mitsuhiko/indicatif#334]
It seems that indicatif has an extra line after the progress bar, which might look weird to some users. Comparison below:

**Yarn**

![image](https://user-images.githubusercontent.com/12389383/146397657-babc5011-afb8-44d0-bcae-19202ec42fe6.png)

**Cargo**

![image](https://user-images.githubusercontent.com/12389383/146397809-8b9f59ae-606e-4c98-abc3-92014de58c3b.png)

**Indicatif**

![image](https://user-images.githubusercontent.com/12389383/146397893-a118e03d-ef11-4ca0-958b-a54b6d7b49ff.png)

**Comment by djc** [comment]
I suppose this might be a regression from #319, would you mind checking? If not, I'd be open to PRs to fix this, though ideally we would some digging first to see if there was a good reason to do this.

**Comment by redzic** [comment]
It was always printed with an extra line, even before #319

**Comment by djc** [comment]
@mitsuhiko do you remember context/rationale for this?

**Comment by sigmaSd** [comment]
I think it was just easier to implement because indicatif supports multiple lines

Here is my attempt to make it work, the general idea is to not append a '\n' to the last line, and fix the math for it (changes console and indicatif)

```patch
diff --git a/src/term.rs b/src/term.rs
index 56287dc..2d8cee1 100644
--- a/src/term.rs
+++ b/src/term.rs
@@ -435,12 +435,14 @@ impl Term {
     /// This positions the cursor at the beginning of the first line
     /// that was cleared.
     pub fn clear_last_lines(&self, n: usize) -> io::Result<()> {
-        self.move_cursor_up(n)?;
-        for _ in 0..n {
+        self.move_cursor_up(n.saturating_sub(1))?;
+        for i in 0..n {
             self.clear_line()?;
-            self.move_cursor_down(1)?;
+            if i + 1 != n {
+                self.move_cursor_down(1)?;
+            }
         }
-        self.move_cursor_up(n)?;
+        self.move_cursor_up(n.saturating_sub(1))?;
         Ok(())
     }
 
diff --git a/src/draw_target.rs b/src/draw_target.rs
index 704026a..949c4e1 100644
--- a/src/draw_target.rs
+++ b/src/draw_target.rs
@@ -389,8 +389,13 @@ impl ProgressDrawState {
     }
 
     pub fn draw_to_term(&self, term: &Term) -> io::Result<()> {
-        for line in &self.lines {
-            term.write_line(line)?;
+        let len = self.lines.len();
+        for (idx, line) in self.lines.iter().enumerate() {
+            if idx + 1 != len {
+                term.write_line(line)?;
+            } else {
+                term.write_str(line)?;
+            }
         }
         Ok(())
    }
```

**Comment by djc** [comment]
I'm fine with reviewing changes along these lines if someone submits a PR.
