### ISSUE TITLE
MultiProgress bar flickers

### ISSUE THREAD

**Issue by inv2004** [mitsuhiko/indicatif#42]
Hello,
My program updates bar quite heavy and I found that it cause MultiProgressBar looks quite bad - it flickers all the time.
I run examples from the crate and see the same problem for multibar and finebars.

Did check examples in windows console, but I see the same problem with my program on linux+putty.

I suppose it could be connected to https://github.com/mitsuhiko/indicatif/issues/18

Regards,

**Comment by mitsuhiko** [comment]
I think this should be significantly better in new versions. If it still flickers please open a new issue.
