### ISSUE TITLE
Easy way to create cool progress bars

### ISSUE THREAD

**Issue by spease** [mitsuhiko/indicatif#43]
I briefly tried out the library and was disappointed by the default progress bar. It'd be nice if the GIFs were linked to an example of the progress bar that it's showing.

**Comment by c-edw** [comment]
Yep, or maybe some presets would be nice.

**Comment by 0xcaff** [comment]
The examples are in the examples folder https://github.com/mitsuhiko/indicatif/tree/master/examples

**Comment by mitsuhiko** [comment]
All the examples are listed in the folder. I hope this helps.
