### ISSUE TITLE
Compilation fails on Windows

### ISSUE THREAD

**Issue by jmcomets** [mitsuhiko/indicatif#5]
Issue is pretty simple, I'm getting the following compilation error on Windows. I have the latest `rustc` and am getting the error on both `nightly` and `stable`.

```
error: no method named `as_raw_handle` found for type `{integer}` in the current scope
  --> [cargo installation directory]\indicatif-0.3.1\src\term\windows.rs:19:28
   |
19 |         GetConsoleMode(out.as_raw_handle(), &mut out) != 0
   |                            ^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `indicatif`.
```

[Link to source code](https://github.com/mitsuhiko/indicatif/blob/master/src/term/windows.rs#L19)

**Comment by mitsuhiko** [comment]
Fixed it. Sorry for that.
