### ISSUE TITLE
Indicatif does not work properly with crossbeam scoped threads

### ISSUE THREAD

**Issue by gnzlbg** [mitsuhiko/indicatif#58]
See https://github.com/crossbeam-rs/crossbeam/issues/180

Doing a `std::thread::spawn` inside a `crossbeam::scope(|s| s.spawn(|| std::thread::spawn(|| ...))` should be necessary.

The following gist contains two files, works.rs works properly, fails.rs produces no output.

https://gist.github.com/gnzlbg/09d7e546df2215bee83fc5fe02840292

**Comment by mitsuhiko** [comment]
Yeah, this is not great but I have no good idea how to improve this at the moment.

**Comment by huytd** [comment]
I guess this is not indicatif problem https://github.com/crossbeam-rs/crossbeam/issues/180

@gnzlbg should we close the ticket?

**Comment by gnzlbg** [comment]
Yes :) Sorry for not closing it before!
