### ISSUE TITLE
No output on MSYS terminals

### ISSUE THREAD

**Issue by alexcrichton** [mitsuhiko/indicatif#60]
When using an MSYS terminal on Windows I unfortunately get no output when using `indicatif` which can be seen notably by executing the examples. Opening up a prompt and executing `cargo run --example log` unfortunately produces no output :(

**Comment by mitsuhiko** [comment]
Any ideas what might cause this? I currently don’t have a windows machine to test this.

**Comment by alexcrichton** [comment]
It looks like this is because when the output is not classified as a terminal it produces no output. I was able to see this behavior on Unix by doing `cargo run --example log 2>&1 | head -n 1000`, which also produced no output. On Windows this comes from the fact that [`is_term` returns false](https://github.com/mitsuhiko/indicatif/blob/950091d1b1683a88e01c4d4975f591009f56322b/src/progress.rs#L131) which is in turn [because it only recognizes true windows consoles](https://github.com/mitsuhiko/console/blob/d2eae6b1861870e8e0e569f9a82104aac6040c49/src/windows_term.rs#L30-L35), not MSYS ones.


In light of that this is sort of two bugs:

* First, `indicatif` produces no output when the output isn't classified as a terminal (although this may be a feature, not a bug?)
* Second, `console` doesn't look to have support for MSYS terminals. An example of detecting whether we're on a terminal for windows I think is in the [`atty` crate](https://github.com/softprops/atty/blob/d4e5d2ebf0ca1c29464dcc51b48de863431cb715/src/lib.rs#L53-L81), notably having a [bunch of weird code for `msys`](https://github.com/softprops/atty/blob/d4e5d2ebf0ca1c29464dcc51b48de863431cb715/src/lib.rs#L104-L141)
