### ISSUE TITLE
Progress bar and spinner won't update without .inc(1)

### ISSUE THREAD

**Issue by andreivasiliu** [mitsuhiko/indicatif#74]
This commit: https://github.com/mitsuhiko/indicatif/commit/7a13000e5d3e8a83d3f0ca9438c269ff23ef751e has made it so that unless there's a change to the current value, no update will happen. This means that, unless I also want to increase the value:
* .set_message() has no effect
* .tick() has no effect
* .set_style() has no effect
* .set_length() has no effect

An immediate fix would be to make ProgressState.draw_delta and ProgressState.draw_next default to 0 instead of 1, so that all updates are applied immediately by default, and let the draw delta behavior be opt-in for those who need performance.

A better fix would be to apply this draw delta logic only to .inc() calls, but I can't see an easy way to do that. Alternatively, keep another counter that gets updated every time .update_and_draw() is called, and track that against draw_delta.

If you have an idea for how to approach this I can work on a pull request if you'd like.

**Comment by andreivasiliu** [comment]
+@cthachuk who authored the original commit

**Comment by cthachuk** [comment]
@andreivasiliu yes, these use cases were overlooked when draw delta was implemented.  That feature should be opt-in, so this is a bug in those case.  I think your immediate fix works.  I couldn't think of an easy way to opt-in only for `.inc()` calls, but that would be great if you think of a solution / work on a PR.

**Comment by andreivasiliu** [comment]
I was thinking of this:
* if new_pos <= old_pos: always draw
  * In other words, it was either `.inc(0)` or some other non-inc() operation
* if new_pos > old_pos: draw based on draw_delta
  * In other words, it was one of `.inc(x) if x > 0` or `.set_pos()`

But then I realized that although your fastbar example only calls `.inc(1)` in that gigantic for loop, people might want to set a custom message for every iteration as well, and they won't have any way to take advantage of this optimization.

I'll just make the default delta be 0, and add documentation that mentions everything else will be suppressed until enough `.inc()` calls are made if draw_delta >= 1.
