### ISSUE TITLE
document all color options

### ISSUE THREAD

**Issue by Luro02** [mitsuhiko/indicatif#84]
There is for some reason no documentation, of which color options are available.

**Comment by mitsuhiko** [comment]
Can you clarify what you mean by that? The color system is documented here: https://docs.rs/console/0.7.5/console/

**Comment by Luro02** [comment]
When I create a progressbar I'd look in the documentation of this crate (obviously) for color options and not in a separate crate?!😐

**Comment by mitsuhiko** [comment]
That’s why I want to know what you mean with color options. Which colorization documentation are you after?

**Comment by Luro02** [comment]
Oh, by color options, I mean what colors can be used to change the color of the progressbar (like "red", "green", "yellow" ....)
