### ISSUE TITLE
Colorized output is dependent on stdout being a tty

### ISSUE THREAD

**Issue by jmgao** [mitsuhiko/indicatif#86]
It seems that the default implementation draws to stderr, but whether the output is colorized is dependent on [whether stdout is a tty](https://github.com/mitsuhiko/clicolors-control/blob/master/src/unix.rs#L5), so if you do something like `foo > log`, you get progress bars, but they're uncolored.

I'm not sure if there's a reasonable fix here without a lot of rearchitecting: it seems to me that console needs to be in charge of printing a styled string, to be able to know whether it should be colorized or not.

**Comment by mitsuhiko** [comment]
You can import clicolors-control and override it if you want a different behavior.

**Comment by kpcyrd** [comment]
Would it make sense to use the draw target for tty detection?

**Comment by kpcyrd** [comment]
In case somebody else runs into the same issue, it's now:
```rust
console::set_colors_enabled(true);
```
